#! /bin/sh
case "$1" in
    start)
    echo "loading scull_load..."
    start-stop-daemon --start --name scull_load --startas /usr/bin/scull_load
    echo "Loading module_load..."
    start-stop-daemon --startas --name module_load --startas /usr/bin/module_load --faulty 
    echo "Modules loaded."
    modprobe hello
     ;;
    stop)
    echo "Unloading scull module..."
    start-stop-daemon --stop -n scull_unload 
    echo "Unloading faulty module..."
    start-stop-daemon --stop -n module_unload --faulty
    echo "Modules unloaded."
    rmmod hello
    ;;
    *)
    echo "Usage: "$0" {Start|Stop}"
    exit 1

esac

exit 0