#! /bin/sh

STOP_SIGNAL=SIGTERM

case "$1" in
    start)
    echo "loading scull_load..."
    start-stop-daemon --start --name scull_load --startas /usr/bin/scull_load
    #start-stop-daemon -S -n scull_load -a /usr/bin/scull_load
    echo "Loading module_load..."
    #start-stop-daemon -S -n module_load -a /usr/bin/module_load -- faulty
    start-stop-daemon --start --name module_load --startas /usr/bin/module_load -- faulty  
    echo "Modules loaded."
    modprobe hello
     ;;
    stop)
    echo "Unloading scull module..."
    start-stop-daemon --start -n scull_unload --startas /usr/bin/scull_unload 
    #start-stop-daemon -S -n scull_unload
    echo "Unloading faulty module..."
    #start-stop-daemon -S -n module_unload -- faulty
    start-stop-daemon --start -n module_unload --startas /usr/bin/module_unload -- faulty 
    echo "Modules unloaded."
    rmmod hello
    ;;
    *)
    echo "Usage: "$0" {Start|Stop}"
    exit 1

esac

exit 0